In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [29]:
ecom_Data_ = pd.read_csv(r"C:\Users\moham\Downloads\rfm_data (1).csv")

In [31]:
ecom_Data_

,CustomerID,PurchaseDate,TransactionAmount,ProductInformation,OrderID,Location
0,8814,2023-04-11,943.31,Product C,890075,Tokyo
1,2188,2023-04-11,463.70,Product A,176819,London
2,4608,2023-04-11,80.28,Product A,340062,New York
3,2559,2023-04-11,221.29,Product A,239145,London
4,9482,2023-04-11,739.56,Product A,194545,Paris
...,...,...,...,...,...,...
995,2970,2023-06-10,759.62,Product B,275284,London
996,6669,2023-06-10,941.50,Product C,987025,New York
997,8836,2023-06-10,545.36,Product C,512842,London
998,1440,2023-06-10,729.94,Product B,559753,Paris
999,4759,2023-06-10,804.28,Product D,467544,New York

In [11]:
### firstly lets select the columns required for RFM ANALYSIS
## cutsomer id 
## PurchaseDate for the recency
## TransactionAmount for monetory
##  OrderID for frequency

In [33]:
ecom_Data_new = ecom_Data_.drop(columns=["ProductInformation","Location"],axis=1)

In [35]:
ecom_Data_new

     CustomerID PurchaseDate  TransactionAmount  OrderID
0          8814   2023-04-11             943.31   890075
1          2188   2023-04-11             463.70   176819
2          4608   2023-04-11              80.28   340062
3          2559   2023-04-11             221.29   239145
4          9482   2023-04-11             739.56   194545
..          ...          ...                ...      ...
995        2970   2023-06-10             759.62   275284
996        6669   2023-06-10             941.50   987025
997        8836   2023-06-10             545.36   512842
998        1440   2023-06-10             729.94   559753
999        4759   2023-06-10             804.28   467544

[1000 rows x 4 columns]

In [37]:
ecom_Data_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         1000 non-null   int64
 1   PurchaseDate       1000 non-null   object
 2   TransactionAmount  1000 non-null   float64
 3   OrderID            1000 non-null   int64
dtypes: float64(1), int64(2), object(1)
memory usage: 31.4+ KB

In [39]:
## 
ecom_Data_new.duplicated().sum()

0

In [41]:
ecom_Data_new.isnull().sum()

CustomerID           0
PurchaseDate         0
TransactionAmount    0
OrderID              0
dtype: int64

In [50]:
## changing the datetime value from object to datetime
ecom_Data_new["PurchaseDate"] = pd.to_datetime(ecom_Data_new["PurchaseDate"])

In [52]:
ecom_Data_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         1000 non-null   int64
 1   PurchaseDate       1000 non-null   datetime64[ns]
 2   TransactionAmount  1000 non-null   float64
 3   OrderID            1000 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 31.4 KB

In [58]:
ecom_Data_new["PurchaseDate"]

0     2023-04-11
1     2023-04-11
2     2023-04-11
3     2023-04-11
4     2023-04-11
         ...
995   2023-06-10
996   2023-06-10
997   2023-06-10
998   2023-06-10
999   2023-06-10
Name: PurchaseDate, Length: 1000, dtype: datetime64[ns]

In [56]:
ecom_Data_new["PurchaseDate"].max()

Timestamp('2023-06-10 00:00:00')

In [60]:
ecom_Data_new["PurchaseDate"].describe().T

count                          1000
mean     2023-05-10 07:27:50.400000
min             2023-04-11 00:00:00
25%             2023-04-26 00:00:00
50%             2023-05-09 00:00:00
75%             2023-05-26 00:00:00
max             2023-06-10 00:00:00
Name: PurchaseDate, dtype: object

In [74]:
import datetime as dt
new_date = dt.datetime(2023,6,11)

In [76]:
new_date

datetime.datetime(2023, 6, 11, 0, 0)

In [80]:
##changing the column names into  RFM
ecom_Data_new.rename(columns={"PurchaseDate":"RECENCY","TransactionAmount":"MONETORY","OrderID":"FREQUENCY"},inplace=True)

In [82]:
ecom_Data_new

     CustomerID    RECENCY  MONETORY  FREQUENCY
0          8814 2023-04-11    943.31     890075
1          2188 2023-04-11    463.70     176819
2          4608 2023-04-11     80.28     340062
3          2559 2023-04-11    221.29     239145
4          9482 2023-04-11    739.56     194545
..          ...        ...       ...        ...
995        2970 2023-06-10    759.62     275284
996        6669 2023-06-10    941.50     987025
997        8836 2023-06-10    545.36     512842
998        1440 2023-06-10    729.94     559753
999        4759 2023-06-10    804.28     467544

[1000 rows x 4 columns]

In [86]:
ecom_Data_new = ecom_Data_new.groupby("CustomerID").agg({'RECENCY':lambda x:(new_date-x.max()).days,
                                                        'MONETORY':lambda x : x.sum(),
                                                        'FREQUENCY': lambda x : x.count()
    
})

In [92]:
ecom_Data_new.reset_index()

     CustomerID  RECENCY  MONETORY  FREQUENCY
0          1011       34   1129.02          2
1          1025       22    359.29          1
2          1029        1    704.99          1
3          1046       44    859.82          1
4          1049       14    225.72          1
..          ...      ...       ...        ...
941        9941       43    960.53          1
942        9950       39    679.11          1
943        9954       13    798.01          1
944        9985       58     36.10          1
945        9991       31    626.81          1

[946 rows x 4 columns]

In [94]:
ecom_Data_new["FREQUENCY"].value_counts()

FREQUENCY
1    895
2     48
3      3
Name: count, dtype: int64

In [96]:
ecom_Data_new["RECENCY"].value_counts()

RECENCY
38    25
51    23
6     23
13    22
45    22
      ..
21     9
28     9
61     7
30     7
52     6
Name: count, Length: 61, dtype: int64

In [98]:
ecom_Data_new.describe().T

,count,mean,std,min,25%,50%,75%,max
RECENCY,946.0,30.983087,17.318484,1.00,15.00,32.000,45.000,61.00
MONETORY,946.0,542.999799,324.382398,12.13,266.64,542.895,782.695,2379.45
FREQUENCY,946.0,1.057082,0.245418,1.00,1.00,1.000,1.000,3.00

In [104]:
## based on the core lets do a quantile cut
quantile = ecom_Data_new.quantile(q=[0.25,0.50,0.75])
quantile.to_dict()

{'RECENCY': {0.25: 15.0, 0.5: 32.0, 0.75: 45.0},
 'MONETORY': {0.25: 266.64, 0.5: 542.895, 0.75: 782.6949999999999},
 'FREQUENCY': {0.25: 1.0, 0.5: 1.0, 0.75: 1.0}}

In [ ]:
### now giving a score for recency frequency and monetory
# lower the recency better the score 
# higher the frequency better the score

In [106]:
def recency_Score(x,q,d):
    if x<=d[q][0.25]:
        return 1
    elif x<=d[q][0.50]:
        return 2
    elif x<=d[q][0.75]:
        return 3
    else:
        return 4

In [108]:
def freq_monet_score(x,q,d):
    if x<=d[q][0.25]:
        return 4
    elif x<=d[q][0.50]:
        return 3
    elif x<=d[q][0.75]:
        return 2
    else:
        return 1

In [110]:
ecom_Data_new["Recency_score"] = ecom_Data_new["RECENCY"].apply(recency_Score,args=("RECENCY",quantile))
ecom_Data_new["frequency_Score"] = ecom_Data_new["FREQUENCY"].apply(freq_monet_score,args=("FREQUENCY",quantile))
ecom_Data_new["monetory_Score"] = ecom_Data_new["MONETORY"].apply(freq_monet_score,args=("MONETORY",quantile))

In [112]:
ecom_Data_new

,RECENCY,MONETORY,FREQUENCY,Recency_score,frequency_Score,monetory_Score
CustomerID,,,,,,
1011,34,1129.02,2,3,1,1
1025,22,359.29,1,2,4,3
1029,1,704.99,1,1,4,2
1046,44,859.82,1,3,4,1
1049,14,225.72,1,1,4,4
...,...,...,...,...,...,...
9941,43,960.53,1,3,4,1
9950,39,679.11,1,3,4,2
9954,13,798.01,1,1,4,1
9985,58,36.10,1,4,4,4
9991,31,626.81,1,2,4,2

In [129]:
## ading the recency frequency monetory score al togehter
ecom_Data_new["RFM_SCORE"] = ecom_Data_new[["Recency_score","frequency_Score","monetory_Score"]].sum(axis=1)

In [131]:
ecom_Data_new

,RECENCY,MONETORY,FREQUENCY,Recency_score,frequency_Score,monetory_Score,RFM_SCORE
CustomerID,,,,,,,
1011,34,1129.02,2,3,1,1,5
1025,22,359.29,1,2,4,3,9
1029,1,704.99,1,1,4,2,7
1046,44,859.82,1,3,4,1,8
1049,14,225.72,1,1,4,4,9
...,...,...,...,...,...,...,...
9941,43,960.53,1,3,4,1,8
9950,39,679.11,1,3,4,2,9
9954,13,798.01,1,1,4,1,6
9985,58,36.10,1,4,4,4,12
9991,31,626.81,1,2,4,2,8

In [133]:
## based on this score giving a loyality badge
loyality_badges = ["PLATINUM","GOLD","SILVER","BRONZE"]
ecom_Data_new["Loyality_Badge"] = pd.qcut(ecom_Data_new["RFM_SCORE"],q=4,labels =loyality_badges)

In [135]:
ecom_Data_new

,RECENCY,MONETORY,FREQUENCY,Recency_score,frequency_Score,monetory_Score,RFM_SCORE,Loyality_Badge
CustomerID,,,,,,,,
1011,34,1129.02,2,3,1,1,5,PLATINUM
1025,22,359.29,1,2,4,3,9,GOLD
1029,1,704.99,1,1,4,2,7,PLATINUM
1046,44,859.82,1,3,4,1,8,PLATINUM
1049,14,225.72,1,1,4,4,9,GOLD
...,...,...,...,...,...,...,...,...
9941,43,960.53,1,3,4,1,8,PLATINUM
9950,39,679.11,1,3,4,2,9,GOLD
9954,13,798.01,1,1,4,1,6,PLATINUM
9985,58,36.10,1,4,4,4,12,BRONZE
9991,31,626.81,1,2,4,2,8,PLATINUM

In [137]:
# dropping columns which arent required
ecom_Data_new.drop(columns=["Recency_score","frequency_Score","monetory_Score","RFM_SCORE"],axis=1,inplace=True)

In [139]:
ecom_Data_new

            RECENCY  MONETORY  FREQUENCY Loyality_Badge
CustomerID
1011             34   1129.02          2       PLATINUM
1025             22    359.29          1           GOLD
1029              1    704.99          1       PLATINUM
1046             44    859.82          1       PLATINUM
1049             14    225.72          1           GOLD
...             ...       ...        ...            ...
9941             43    960.53          1       PLATINUM
9950             39    679.11          1           GOLD
9954             13    798.01          1       PLATINUM
9985             58     36.10          1         BRONZE
9991             31    626.81          1       PLATINUM

[946 rows x 4 columns]

In [143]:
ecom_Data_new["Loyality_Badge"].value_counts()

Loyality_Badge
PLATINUM    381
GOLD        213
BRONZE      181
SILVER      171
Name: count, dtype: int64